#!/bin/bash

drone_help() {
    echo "Drone Development Environment - Command Reference"
    echo ""
    echo "━━━━ QUICK START ━━━━"
    echo "  start_all        - Launch Gazebo + ArduPilot + MAVROS"
    echo "  stop_all         - Stop all drone processes"
    echo "  preflight        - Run preflight checks"
    echo ""
    echo "━━━━ STARTUP ━━━━"
    echo "  start_minimal    - Launch MAVROS only"
    echo "  start_hardware   - Connect to real flight controller"
    echo "  start_gazebo     - Launch Gazebo only"
    echo "  start_ardupilot  - Launch ArduPilot SITL only"
    echo "  start_mavros     - Launch MAVROS only"
    echo ""
    echo "  stop_gazebo / stop_ardupilot / stop_mavros - Stop specific"
    echo "  restart_mavros / restart_gazebo / restart_ardupilot - Restart specific component"
    echo ""
    echo "━━━━ BASIC CONTROL ━━━━"
    echo "  arm / disarm     - Arm/disarm motors"
    echo "  takeoff <alt>    - Takeoff to altitude (meters)"
    echo "  land             - Land the drone"
    echo "  STOP / KILL      - Emergency stop (kills motors)"
    echo ""
    echo "━━━━ FLIGHT MODES ━━━━"
    echo "  guided           - GUIDED mode (for waypoint navigation)"
    echo "  stabilize        - STABILIZE mode (manual flight)"
    echo "  loiter           - LOITER mode (hold position)"
    echo "  rtl              - Return to launch"
    echo "  auto             - AUTO mode (follow mission)"
    echo "  althold          - ALT_HOLD (hold altitude)"
    echo "  poshold          - POS_HOLD (hold position)"
    echo ""
    echo "━━━━ VELOCITY CONTROL ━━━━"
    echo "  vel_linear <x> <y> <z>    - Linear velocity only"
    echo "  vel <lx> <ly> <lz> <ax> <ay> <az> - Full velocity control"
    echo "  vel_stop                   - Stop velocity commands"
    echo ""
    echo "━━━━ MONITORING ━━━━"
    echo "  status           - Full status report"
    echo "  state            - Show flight mode and armed status"
    echo "  pos              - Show GPS position"
    echo "  battery          - Show battery status"
    echo "  topics           - List all MAVROS topics"
    echo "  nodes            - List active ROS2 nodes"
    echo "  check_connection - Verify MAVROS connection"
    echo ""
    echo "━━━━ NAVIGATION ━━━━"
    echo "  goto <lat> <lon> [alt] - Navigate to GPS coordinate"
    echo "  clear_mission    - Clear all waypoints"
    echo ""
    echo "━━━━ PARAMETERS ━━━━"
    echo "  get_param <name> - Get parameter value"
    echo "  set_param <name> <val> - Set parameter"
    echo "  save_params      - Save parameters to EEPROM"
    echo ""
    echo "━━━━ DEVELOPMENT ━━━━"
    echo "  ws               - Go to workspace directory"
    echo "  build            - Build ROS2 workspace"
    echo "  rebuild          - Quick rebuild + source"
    echo "  clean_build      - Clean build from scratch"
    echo "  src              - Source workspace"
    echo "  new_package <name> - Create new ROS2 package"
    echo "  rviz             - Launch RViz"
    echo "  rqt              - Launch rqt"
    echo ""
    echo "━━━━ RECORDING ━━━━"
    echo "  record [name]    - Start recording bag file"
    echo "  playback <name>  - Play back recording"
    echo "  list_bags        - List all recordings"
    echo ""
    echo "━━━━ SAFETY ━━━━"
    echo "  disable_safety_checks  - Disable pre-arm checks (use with caution!)"
    echo "  reenable_safety_checks - Re-enable safety checks"
    echo "  set_geofence <radius>  - Set geofence radius (meters)"
    echo ""
    echo "For more info, see: https://github.com/kienphamh/Raptors-drone-environment"
}

alias help='drone_help'
alias h='drone_help'

echo "Type 'help' to see all available commands"
echo ""